# Generated by Django 5.1.6 on 2025-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_movement_movement_type_alter_product_min_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
