# Generated by Django 5.1.6 on 2025-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='stock_after_movement',
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('استلام', 'استلام'), ('سحب', 'سحب')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
