# Generated by Django 5.2 on 2025-04-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_movement_stock_after_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='quantity_after',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
